
### 회원 가입 (ROLE = ROLE_ADMIN , ROLE_USER)
POST http://localhost:8080/members/signup
Content-Type:application/json

{
  "name": "testName",
  "nickname": "idus",
  "password": "@Abc123456789",
  "tel": "01012345678",
  "email": "test@email.com",
  "gender": "남성",
  "role": "ROLE_ADMIN"
}

### 로그인 (토큰 발급)
POST http://localhost:8080/members/login
Content-Type:application/json

{
  "email": "test@email.com",
  "password": "@Abc123456789"
}


### 맴버 상세정보 보기(유저,어드민)
GET http://localhost:8080/members/personal-info
Authorization: Bearer toekn   // 토큰값 입력


### 주문생성
POST http://localhost:8080/orders
Authorization: Bearer toekn   // 토큰값 입력
Content-Type:application/json

{
  "item": "testItem"
}


### 나의 주문목록 보기(유저,어드민)
GET http://localhost:8080/orders
Authorization: Bearer toekn   // 토큰값 입력



### 마지막 주문 목록을 포함한 맴버리스트 보기(어드민)
// queryParam:  name,email,page,pagesize
// ex http://localhost:8080/admin/members?name:testName
GET http://localhost:8080/admin/members
Authorization: Bearer toekn   // 토큰값 입력


### 회원상세 정보보기(어드민)
// ex http://localhost:8080/admin/members/test@email.com
GET http://localhost:8080/admin/members/{{email}}
Authorization: Bearer toekn   // 토큰값 입력


### 선택 회원 주문목록 보기(어드민)
// ex http://localhost:8080/admin/orders//test@email.com
GET http://localhost:8080/admin/orders/{{userEmail}}
Authorization: Bearer toekn   // 토큰값 입력