spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-db
      settings:
        web-allow-others: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
jwt:
  secretKey: idusApiTest
